### ISSUE TITLE
Multi-switch support

### ISSUE THREAD

**Issue by dkrahmer** [TheAgentK/tuya-mqtt#50]
Support switch devices that contain multiple switches.

Moving the discussion from: PR https://github.com/TheAgentK/tuya-mqtt/pull/49 (unrelated code)

Summary:
I added support for multi-switches in my fork of this repo but did not realize the config schema was based on homebridge-tuya (thanks @tsightler for pointing this out). My solution works but likely does not conform to any previously established standards since I made it up.

I am sure some of my code can still be used but it will need to be modified. I also added device type guessing and mdl guessing logic which I hope can be kept as well since it helps simplify the devices.conf file for common configurations.

This is my working implementation for multi-switches here: https://github.com/dkrahmer/tuya-mqtt/pull/2/files

**Comment by tsightler** [comment]
Yeah, there's a bunch of stuff in there I won't be interested in merging, such as all the template stuff in config.json so I'd need that PR broken way down into the minimal required to support multi-switch.  I don't really understand the need for all of the changes since it's already possible to support multi-switch devices with a custom template so it really only requires some minimal logic to support a type and some basic config options.

**Comment by tsightler** [comment]
Closing this as I have no plans to support this in the near future.
